### ISSUE TITLE
packagist.org

### ISSUE THREAD

**Issue by natewallis** [browserstack/phpunit-browserstack#12]
Need a release of this package on packagist.org - is there a particular reason why it isn't released there?

It seems by simply adding a name to composer.json that the package could be submitted to make it a handy package to add for integrating into browserstack. 

Currently the install method is manual, which is not ideal when deploying to continuous integration tools, it would be better if it could be installed with a simple `composer install`..

**Comment by mohitmun** [comment]
Hi @nwallis,

This code repo demonstrates how to run tests on BrowserStack using phpunit. it's not intended to release anywhere.
In case if you want to integrate Browserstack with any popular CI, checkout our documentation page [here](https://www.browserstack.com/docs?product=automate)
